# -*- coding: utf-8 -*-
"""logistics_reg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DTZMID4GPLk8f3_dqafqc8BDeEsTW6P_
"""

import zipfile
import pandas as pd
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn import linear_model
import matplotlib.pyplot as plt

extract_fol="/content/drive/MyDrive/archive.zip"
dest="/content/drive/MyDrive"
with zipfile.ZipFile(extract_fol,'r') as zip:
      zip.extractall("testing")

data=pd.read_csv("/content/testing/hearing_test.csv")
print(data)
print(data.info)
print(data.describe())
X=data.loc[:,["age","physical_score"]]
Y=data["test_result"]
print(X.shape)
print(Y.shape)

# model buildin
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)
train=linear_model.LogisticRegression(solver="liblinear",multi_class="auto").fit(X_train,Y_train)
score=train.score(X_test,Y_test)
print(score)
data1=pd.DataFrame([[20.0,70.5]])
pred=train.predict(X_test)
print(pred)
plt.bar(pred,Y_test)
plt.xlabel("pred value")
plt.ylabel("origianle val")
plt.legend()